"use strict";
// THIS FILE IS GENERATED BY tools/tools_create_html_file_dict.py 
// DO NOT MODIFY IT                                
// Generated in 2020-02-05 23:22:40                             

window.htmlFileDict = {
    "txtFile"         : "txtFile.html",
    "login"           : "login.html",
    "createUser"      : "createUser.html",
    "filePassword"    : "filePassword.html",
    "chgPassword"     : "chgPassword.html",
    "newFilePassword" : "newFilePassword.html",
    "MyWindow"        : "MyWindow.html",
    "main"            : "main.html"
};