"use strict";
// THIS FILE IS GENERATED BY tools/tools_create_html_file_dict.py 
// DO NOT MODIFY IT                                
// Generated in 2020-02-14 15:13:55                             

window.htmlFileDict = {
    "txtFile"                : "txtFile.html",
    "login"                  : "login.html",
    "createUser"             : "createUser.html",
    "filePassword"           : "filePassword.html",
    "chgPassword"            : "chgPassword.html",
    "newFilePassword"        : "newFilePassword.html",
    "phoneBookContact"       : "phoneBookContact.html",
    "phoneBookFile"          : "phoneBookFile.html",
    "main"                   : "main.html",
    "phoneBookModifyContact" : "phoneBookModifyContact.html"
};