#TODO: check
from enum import Enum
import datetime
import sys
import os

class Language(Enum):
    DEFAULT    = 0
    JAVASCRIPT = 1
    PYTHON     = 2
    BASH       = 3
    CPP        = 4
    HTML       = 5

global __text1
global __default_comment_start_sign, __comment_start_sign
global __default_comment_end_sign  , __comment_end_sign

__text = """{c_start} THIS FILE IS GENERATED BY tools/{file_name} {c_end}
{c_start} DO NOT MODIFY IT                                {c_end}
{c_start} Generated in {now}                             {c_end}"""

__default_comment_start_sign = "//"
__comment_start_sign = {
    Language.PYTHON : "#",
    Language.BASH   : "#",
    Language.HTML   : "<!-- "
}

__default_comment_end_sign = ""
__comment_end_sign         = {
    Language.HTML   : " -->"
}

def generatedby(language: Language):
    data = {
        "now"       : datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "c_start"   : __comment_start_sign.get(language)  or __default_comment_start_sign,
        "c_end"     : __comment_end_sign.get(language)    or __default_comment_end_sign,
        "file_name" : os.path.basename( sys.argv[0] )
    }
    return __text.format(**data)

if __name__ == "__main__":
    print(generatedby(Language.DEFAULT))