"use strict";
// THIS FILE IS GENERATED BY tools/create_html_file_dict.py 
// DO NOT MODIFY IT                                
// Generated in 2020-01-24 13:17:01                             

window.htmlFileDict = {
    "txtFile"     : "txtFile.html",
    "login"       : "login.html",
    "createUser"  : "createUser.html",
    "chgPassword" : "chgPassword.html",
    "MyWindow"    : "MyWindow.html",
    "main"        : "main.html"
};