from .enum2 import Enum2

class ErrorTypeEnum(Enum2):
    #LOCAL
    CONNECTION_ERROR = 101
    LOCAL_CALL_ERROR = 102
    ALREADY_LOGEDIN = 103
    EMPTY_USERNAME_PASSWORD = 104
    PASSWORD_NOT_EQUAL_PASSWORD2 = 105
    PASWORD_PASSWORD2_EMPTY = 106
    PASWORD_PASSWORD2_OLD_PASSWORD_EMPTY = 107
    EMPTY_FILE_FIELD = 108
    DOWNLOAD_ERROR = 109
    CONTACT_ALREADY_IN_LIST = 110
    CONTACT_NOT_FOUND = 111
    SUDDENLY_LOGGED_OUT = 112
    DECRYPTION_FAILURE = 113

    #REMOTE
    MISSING_USERNAME_PASSWORD = 201
    BAD_USERNAME_PASSWORD = 202
    REMOTE_FUNCTION_ERROR = 203
    USER_REGISTRATED = 204
    DISABLED_CREATE_USER = 205
    FILE_EXIST = 206
    FILE_NOT_EXIST = 207