import json
import datetime

from config.tools import configToJsString
from error_object.error_type import ErrorLocEnum
from error_object.get_error_type_dict import getErrorTypesDict
from error_object.error_type_enum import ErrorTypeEnum


def JsGenerator():
    data = {
        "now":datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "file_name":"server/python/js_generator/js_generator.py"
    }
    ret = """'use strict';
// THIS FILE IS GENERATED BY tools/{file_name}
// DO NOT MODIFY IT
// Generated in {now}

""".format(**data)
    ret += configToJsString()
    ret += "\n\n"
    ret += "window.ErrorTypes = " + json.dumps(getErrorTypesDict()) + ";\n"
    ret += "window.ErrorTypeEnum = " + json.dumps(ErrorTypeEnum.toDictKeyByValue()) + ";\n"
    ret += "window.ErrorTypeEnumByValue = " + json.dumps(ErrorTypeEnum.toDictValueByKey()) + ";\n"
    ret += "window.ErrorErrorLocEnum = " + json.dumps(ErrorLocEnum.toDictKeyByValue()) + ";\n"
    ret += "window.ErrorErrorLocEnumByValue = " + json.dumps(ErrorLocEnum.toDictValueByKey()) + ";\n"
    return ret