from .enum2 import Enum2

class ErrorTypeEnum(Enum2):
    #LOCAL
    CONNECTION_ERROR = 101
    LOCAL_CALL_ERROR = 102
    ALREADY_LOGEDIN = 103
    
    #REMOTE
    MISSING_USERNAME_PASSWORD = 201
    BAD_USERNAME_PASSWORD = 202
    REMOTE_FUNCTION_ERROR = 203