#!/usr/bin/env python3

import os
import sys
import re
import pathlib
from datetime import datetime
from mylib.dictgenerator import dictgenerator

global htmlDir, filePath
currDir  = pathlib.Path(__file__).parent.absolute()
htmlDir  = currDir.joinpath("../html/")
filePath = currDir.joinpath("../generated/htmlFileDict.js")


def getHtmls():
    htmls = os.listdir( htmlDir )
    htmls = [x for x in htmls if x.endswith(".html")]
    return htmls

def writeFile():
    htmls = getHtmls()
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    text = """"use strict";
// THIS GENERATED BY toos/create_html_file_dict.py
// DO NOT MODIFY IT
// Generated in {}

""".format(now)
    
    d = { k.rstrip(".html"):k for k in htmls }
    text += dictgenerator("window.htmlFileDict", d)
    
    with open(filePath, "w") as f:
        f.write(text)
    return text

def main():
    text = writeFile()
    print(text)
    print()
    print("Writed to {}".format(filePath))

if "__main__" == __name__:
    main()